INSERT INTO public.field_dictionary (field_key, label, section, form_type, data_type, allowed_roles, read_only_roles) VALUES
('ln_p_companyId', 'Company ID', 'loan_terms', 'details', 'text', ARRAY['admin','csr'], ARRAY[]::text[]),
('ln_p_previousLoanNumber', 'Previous Loan Number', 'loan_terms', 'details', 'text', ARRAY['admin','csr'], ARRAY[]::text[]),
('ln_p_loanCode', 'Loan Code', 'loan_terms', 'details', 'text', ARRAY['admin','csr'], ARRAY[]::text[]),
('ln_p_originalBalance', 'Original Balance', 'loan_terms', 'details', 'currency', ARRAY['admin','csr'], ARRAY[]::text[]),
('ln_p_recordingDate', 'Recording Date', 'loan_terms', 'details', 'date', ARRAY['admin','csr'], ARRAY[]::text[]),
('ln_p_recordingNumber', 'Recording Number', 'loan_terms', 'details', 'text', ARRAY['admin','csr'], ARRAY[]::text[]),
('ln_p_previousAccountNumber', 'Previous Account Number', 'loan_terms', 'details', 'text', ARRAY['admin','csr'], ARRAY[]::text[]),
('ln_p_overpaymentsAppliedTo', 'Overpayments Applied To', 'loan_terms', 'details', 'text', ARRAY['admin','csr'], ARRAY[]::text[]),
('ln_p_relatedPartySearch', 'Related Party Search', 'loan_terms', 'details', 'text', ARRAY['admin','csr'], ARRAY[]::text[]),
('ln_p_ownerOccupied', 'Owner Occupied', 'loan_terms', 'details', 'boolean', ARRAY['admin','csr'], ARRAY[]::text[]),
('ln_p_multiLender', 'Multi-lender', 'loan_terms', 'details', 'boolean', ARRAY['admin','csr'], ARRAY[]::text[]),
('ln_p_passThrough', 'Pass Through', 'loan_terms', 'details', 'boolean', ARRAY['admin','csr'], ARRAY[]::text[]),
('ln_p_loanStatus', 'Loan Status', 'loan_terms', 'details', 'text', ARRAY['admin','csr'], ARRAY[]::text[]),
('ln_p_holdReason', 'Hold Reason', 'loan_terms', 'details', 'text', ARRAY['admin','csr'], ARRAY[]::text[]),
('ln_p_closedReason', 'Closed Reason', 'loan_terms', 'details', 'text', ARRAY['admin','csr'], ARRAY[]::text[]),
('ln_p_documentPrep', 'Document Prep', 'loan_terms', 'details', 'boolean', ARRAY['admin','csr'], ARRAY[]::text[]),
('ln_p_transferIn', 'Transfer In', 'loan_terms', 'details', 'boolean', ARRAY['admin','csr'], ARRAY[]::text[]),
('ln_p_bankruptcy', 'Bankruptcy', 'loan_terms', 'details', 'boolean', ARRAY['admin','csr'], ARRAY[]::text[]),
('ln_p_foreclosure', 'Foreclosure', 'loan_terms', 'details', 'boolean', ARRAY['admin','csr'], ARRAY[]::text[]),
('ln_p_modification', 'Modification', 'loan_terms', 'details', 'boolean', ARRAY['admin','csr'], ARRAY[]::text[]),
('ln_p_forbearance', 'Forbearance', 'loan_terms', 'details', 'boolean', ARRAY['admin','csr'], ARRAY[]::text[]),
('ln_p_assignment', 'Assignment', 'loan_terms', 'details', 'boolean', ARRAY['admin','csr'], ARRAY[]::text[]),
('ln_p_litigation', 'Litigation', 'loan_terms', 'details', 'boolean', ARRAY['admin','csr'], ARRAY[]::text[]),
('ln_p_militarySCRA', 'Military SCRA', 'loan_terms', 'details', 'boolean', ARRAY['admin','csr'], ARRAY[]::text[])
ON CONFLICT (field_key) DO NOTHING;

INSERT INTO public.field_key_migrations (old_key, new_key, status, migrated_at) VALUES
('loan_terms.company_id', 'ln_p_companyId', 'pending', now()),
('loan_terms.previous_loan_number', 'ln_p_previousLoanNumber', 'pending', now()),
('loan_terms.loan_code', 'ln_p_loanCode', 'pending', now()),
('loan_terms.original_balance', 'ln_p_originalBalance', 'pending', now()),
('loan_terms.recording_date', 'ln_p_recordingDate', 'pending', now()),
('loan_terms.recording_number', 'ln_p_recordingNumber', 'pending', now()),
('loan_terms.previous_account_number', 'ln_p_previousAccountNumber', 'pending', now()),
('loan_terms.overpayments_applied_to', 'ln_p_overpaymentsAppliedTo', 'pending', now()),
('loan_terms.related_party_search', 'ln_p_relatedPartySearch', 'pending', now()),
('loan_terms.owner_occupied', 'ln_p_ownerOccupied', 'pending', now()),
('loan_terms.multi_lender', 'ln_p_multiLender', 'pending', now()),
('loan_terms.pass_through', 'ln_p_passThrough', 'pending', now()),
('loan_terms.loan_status', 'ln_p_loanStatus', 'pending', now()),
('loan_terms.hold_reason', 'ln_p_holdReason', 'pending', now()),
('loan_terms.closed_reason', 'ln_p_closedReason', 'pending', now()),
('loan_terms.document_prep', 'ln_p_documentPrep', 'pending', now()),
('loan_terms.transfer_in', 'ln_p_transferIn', 'pending', now()),
('loan_terms.status_bankruptcy', 'ln_p_bankruptcy', 'pending', now()),
('loan_terms.status_foreclosure', 'ln_p_foreclosure', 'pending', now()),
('loan_terms.status_modification', 'ln_p_modification', 'pending', now()),
('loan_terms.status_forbearance', 'ln_p_forbearance', 'pending', now()),
('loan_terms.status_assignment', 'ln_p_assignment', 'pending', now()),
('loan_terms.status_litigation', 'ln_p_litigation', 'pending', now()),
('loan_terms.status_military_scra', 'ln_p_militarySCRA', 'pending', now())
ON CONFLICT DO NOTHING;